<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            [
                'name' => 'Programming',
                'slug' => 'programming',
                'description' => 'Articles about programming languages, coding practices, and software development.',
                'color' => '#3B82F6',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Web Development',
                'slug' => 'web-development',
                'description' => 'Frontend and backend web development tutorials, frameworks, and best practices.',
                'color' => '#10B981',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Mobile Development',
                'slug' => 'mobile-development',
                'description' => 'iOS, Android, and cross-platform mobile app development guides.',
                'color' => '#8B5CF6',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'Artificial Intelligence',
                'slug' => 'artificial-intelligence',
                'description' => 'AI, machine learning, deep learning, and neural networks articles.',
                'color' => '#EF4444',
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'DevOps',
                'slug' => 'devops',
                'description' => 'CI/CD, Docker, Kubernetes, cloud infrastructure, and deployment strategies.',
                'color' => '#F59E0B',
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'Database',
                'slug' => 'database',
                'description' => 'Database design, SQL, NoSQL, optimization, and management tutorials.',
                'color' => '#06B6D4',
                'sort_order' => 6,
                'is_active' => true,
            ],
            [
                'name' => 'Cybersecurity',
                'slug' => 'cybersecurity',
                'description' => 'Security best practices, vulnerabilities, encryption, and ethical hacking.',
                'color' => '#EC4899',
                'sort_order' => 7,
                'is_active' => true,
            ],
            [
                'name' => 'Tech News',
                'slug' => 'tech-news',
                'description' => 'Latest technology news, industry updates, and tech trends.',
                'color' => '#6366F1',
                'sort_order' => 8,
                'is_active' => true,
            ],
            [
                'name' => 'Cloud Computing',
                'slug' => 'cloud-computing',
                'description' => 'Cloud platforms, services, architecture, and migration strategies.',
                'color' => '#14B8A6',
                'sort_order' => 9,
                'is_active' => true,
            ],
            [
                'name' => 'Data Science',
                'slug' => 'data-science',
                'description' => 'Data analysis, visualization, statistics, and big data technologies.',
                'color' => '#F97316',
                'sort_order' => 10,
                'is_active' => true,
            ],
            [
                'name' => 'Blockchain',
                'slug' => 'blockchain',
                'description' => 'Blockchain technology, cryptocurrencies, smart contracts, and Web3.',
                'color' => '#84CC16',
                'sort_order' => 11,
                'is_active' => true,
            ],
            [
                'name' => 'Game Development',
                'slug' => 'game-development',
                'description' => 'Game design, engines, graphics, and development tools.',
                'color' => '#A855F7',
                'sort_order' => 12,
                'is_active' => true,
            ],
            [
                'name' => 'UI/UX Design',
                'slug' => 'ui-ux-design',
                'description' => 'User interface design, user experience, design systems, and prototyping.',
                'color' => '#EC4899',
                'sort_order' => 13,
                'is_active' => true,
            ],
            [
                'name' => 'Software Architecture',
                'slug' => 'software-architecture',
                'description' => 'System design, patterns, scalability, and architectural decisions.',
                'color' => '#0EA5E9',
                'sort_order' => 14,
                'is_active' => true,
            ],
            [
                'name' => 'Testing & QA',
                'slug' => 'testing-qa',
                'description' => 'Testing strategies, automation, quality assurance, and test frameworks.',
                'color' => '#22C55E',
                'sort_order' => 15,
                'is_active' => true,
            ],
            [
                'name' => 'Open Source',
                'slug' => 'open-source',
                'description' => 'Open source projects, contributions, and community-driven development.',
                'color' => '#F59E0B',
                'sort_order' => 16,
                'is_active' => true,
            ],
            [
                'name' => 'Career & Learning',
                'slug' => 'career-learning',
                'description' => 'Career advice, learning resources, coding bootcamps, and skill development.',
                'color' => '#8B5CF6',
                'sort_order' => 17,
                'is_active' => true,
            ],
            [
                'name' => 'Tools & Productivity',
                'slug' => 'tools-productivity',
                'description' => 'Development tools, IDEs, productivity tips, and workflow optimization.',
                'color' => '#06B6D4',
                'sort_order' => 18,
                'is_active' => true,
            ],
            [
                'name' => 'Frontend Frameworks',
                'slug' => 'frontend-frameworks',
                'description' => 'React, Vue, Angular, Svelte, and other modern frontend frameworks.',
                'color' => '#3B82F6',
                'sort_order' => 19,
                'is_active' => true,
            ],
            [
                'name' => 'Backend Development',
                'slug' => 'backend-development',
                'description' => 'Server-side development, APIs, microservices, and backend architectures.',
                'color' => '#10B981',
                'sort_order' => 20,
                'is_active' => true,
            ],
            [
                'name' => 'API Development',
                'slug' => 'api-development',
                'description' => 'REST APIs, GraphQL, API design, documentation, and integration.',
                'color' => '#8B5CF6',
                'sort_order' => 21,
                'is_active' => true,
            ],
            [
                'name' => 'Performance Optimization',
                'slug' => 'performance-optimization',
                'description' => 'Website performance, speed optimization, caching, and load time improvement.',
                'color' => '#EF4444',
                'sort_order' => 22,
                'is_active' => true,
            ],
            [
                'name' => 'Networking',
                'slug' => 'networking',
                'description' => 'Network protocols, TCP/IP, HTTP/HTTPS, DNS, and network security.',
                'color' => '#F59E0B',
                'sort_order' => 23,
                'is_active' => true,
            ],
            [
                'name' => 'Internet of Things',
                'slug' => 'internet-of-things',
                'description' => 'IoT devices, sensors, embedded systems, and smart home technologies.',
                'color' => '#06B6D4',
                'sort_order' => 24,
                'is_active' => true,
            ],
            [
                'name' => 'Hardware & Electronics',
                'slug' => 'hardware-electronics',
                'description' => 'Computer hardware, electronics, Arduino, Raspberry Pi, and embedded systems.',
                'color' => '#EC4899',
                'sort_order' => 25,
                'is_active' => true,
            ],
            [
                'name' => 'Operating Systems',
                'slug' => 'operating-systems',
                'description' => 'Linux, Windows, macOS, Unix, and OS administration and configuration.',
                'color' => '#6366F1',
                'sort_order' => 26,
                'is_active' => true,
            ],
            [
                'name' => 'Version Control',
                'slug' => 'version-control',
                'description' => 'Git, GitHub, GitLab, version control workflows, and collaboration tools.',
                'color' => '#14B8A6',
                'sort_order' => 27,
                'is_active' => true,
            ],
            [
                'name' => 'Documentation',
                'slug' => 'documentation',
                'description' => 'Technical writing, API documentation, code documentation, and guides.',
                'color' => '#F97316',
                'sort_order' => 28,
                'is_active' => true,
            ],
            [
                'name' => 'E-commerce',
                'slug' => 'e-commerce',
                'description' => 'Online stores, payment gateways, shopping carts, and e-commerce platforms.',
                'color' => '#84CC16',
                'sort_order' => 29,
                'is_active' => true,
            ],
            [
                'name' => 'Content Management',
                'slug' => 'content-management',
                'description' => 'CMS platforms, headless CMS, content strategy, and content delivery.',
                'color' => '#A855F7',
                'sort_order' => 30,
                'is_active' => true,
            ],
            [
                'name' => 'Analytics & Tracking',
                'slug' => 'analytics-tracking',
                'description' => 'Web analytics, user tracking, data analysis, and business intelligence.',
                'color' => '#EC4899',
                'sort_order' => 31,
                'is_active' => true,
            ],
            [
                'name' => 'Monitoring & Logging',
                'slug' => 'monitoring-logging',
                'description' => 'Application monitoring, error tracking, logging, and observability tools.',
                'color' => '#0EA5E9',
                'sort_order' => 32,
                'is_active' => true,
            ],
            [
                'name' => 'Automation',
                'slug' => 'automation',
                'description' => 'Task automation, scripting, CI/CD pipelines, and workflow automation.',
                'color' => '#22C55E',
                'sort_order' => 33,
                'is_active' => true,
            ],
            [
                'name' => 'Scripting',
                'slug' => 'scripting',
                'description' => 'Shell scripting, Python scripts, automation scripts, and command-line tools.',
                'color' => '#F59E0B',
                'sort_order' => 34,
                'is_active' => true,
            ],
            [
                'name' => 'Web Servers',
                'slug' => 'web-servers',
                'description' => 'Nginx, Apache, server configuration, load balancing, and reverse proxies.',
                'color' => '#8B5CF6',
                'sort_order' => 35,
                'is_active' => true,
            ],
            [
                'name' => 'Virtualization',
                'slug' => 'virtualization',
                'description' => 'Virtual machines, containers, Docker, Kubernetes, and containerization.',
                'color' => '#06B6D4',
                'sort_order' => 36,
                'is_active' => true,
            ],
            [
                'name' => 'Cryptography',
                'slug' => 'cryptography',
                'description' => 'Encryption, hashing, digital signatures, SSL/TLS, and cryptographic algorithms.',
                'color' => '#EF4444',
                'sort_order' => 37,
                'is_active' => true,
            ],
            [
                'name' => 'Web Standards',
                'slug' => 'web-standards',
                'description' => 'HTML5, CSS3, W3C standards, accessibility, and web best practices.',
                'color' => '#10B981',
                'sort_order' => 38,
                'is_active' => true,
            ],
            [
                'name' => 'Progressive Web Apps',
                'slug' => 'progressive-web-apps',
                'description' => 'PWA development, service workers, offline functionality, and app-like experiences.',
                'color' => '#3B82F6',
                'sort_order' => 39,
                'is_active' => true,
            ],
            [
                'name' => 'Serverless',
                'slug' => 'serverless',
                'description' => 'Serverless architecture, AWS Lambda, Azure Functions, and FaaS platforms.',
                'color' => '#6366F1',
                'sort_order' => 40,
                'is_active' => true,
            ],
            [
                'name' => 'Microservices',
                'slug' => 'microservices',
                'description' => 'Microservices architecture, service mesh, distributed systems, and scalability.',
                'color' => '#14B8A6',
                'sort_order' => 41,
                'is_active' => true,
            ],
            [
                'name' => 'Real-time Applications',
                'slug' => 'real-time-applications',
                'description' => 'WebSockets, real-time communication, chat applications, and live updates.',
                'color' => '#F97316',
                'sort_order' => 42,
                'is_active' => true,
            ],
            [
                'name' => 'Search Engine Optimization',
                'slug' => 'search-engine-optimization',
                'description' => 'SEO strategies, keyword research, on-page optimization, and technical SEO.',
                'color' => '#84CC16',
                'sort_order' => 43,
                'is_active' => true,
            ],
            [
                'name' => 'Web Accessibility',
                'slug' => 'web-accessibility',
                'description' => 'WCAG compliance, ARIA, accessible design, and inclusive web development.',
                'color' => '#A855F7',
                'sort_order' => 44,
                'is_active' => true,
            ],
            [
                'name' => 'Code Quality',
                'slug' => 'code-quality',
                'description' => 'Code reviews, linting, formatting, best practices, and maintainable code.',
                'color' => '#EC4899',
                'sort_order' => 45,
                'is_active' => true,
            ],
            [
                'name' => 'Design Patterns',
                'slug' => 'design-patterns',
                'description' => 'Software design patterns, architectural patterns, and coding patterns.',
                'color' => '#0EA5E9',
                'sort_order' => 46,
                'is_active' => true,
            ],
            [
                'name' => 'Code Review',
                'slug' => 'code-review',
                'description' => 'Code review practices, pull requests, code quality, and collaboration.',
                'color' => '#22C55E',
                'sort_order' => 47,
                'is_active' => true,
            ],
            [
                'name' => 'Debugging',
                'slug' => 'debugging',
                'description' => 'Debugging techniques, tools, error handling, and troubleshooting.',
                'color' => '#F59E0B',
                'sort_order' => 48,
                'is_active' => true,
            ],
            [
                'name' => 'Package Management',
                'slug' => 'package-management',
                'description' => 'npm, yarn, Composer, pip, package managers, and dependency management.',
                'color' => '#8B5CF6',
                'sort_order' => 49,
                'is_active' => true,
            ],
            [
                'name' => 'Build Tools',
                'slug' => 'build-tools',
                'description' => 'Webpack, Vite, Gulp, Grunt, build automation, and asset compilation.',
                'color' => '#06B6D4',
                'sort_order' => 50,
                'is_active' => true,
            ],
            [
                'name' => 'WebAssembly',
                'slug' => 'webassembly',
                'description' => 'WebAssembly, WASM, high-performance web applications, and native code in browsers.',
                'color' => '#EF4444',
                'sort_order' => 51,
                'is_active' => true,
            ],
            [
                'name' => 'GraphQL',
                'slug' => 'graphql',
                'description' => 'GraphQL queries, schemas, Apollo, Relay, and GraphQL best practices.',
                'color' => '#10B981',
                'sort_order' => 52,
                'is_active' => true,
            ],
            [
                'name' => 'REST APIs',
                'slug' => 'rest-apis',
                'description' => 'RESTful API design, endpoints, HTTP methods, and API best practices.',
                'color' => '#3B82F6',
                'sort_order' => 53,
                'is_active' => true,
            ],
            [
                'name' => 'WebSockets',
                'slug' => 'websockets',
                'description' => 'WebSocket protocol, real-time communication, Socket.io, and live connections.',
                'color' => '#6366F1',
                'sort_order' => 54,
                'is_active' => true,
            ],
            [
                'name' => 'Responsive Design',
                'slug' => 'responsive-design',
                'description' => 'Mobile-first design, responsive layouts, breakpoints, and cross-device compatibility.',
                'color' => '#14B8A6',
                'sort_order' => 55,
                'is_active' => true,
            ],
            [
                'name' => 'Typography',
                'slug' => 'typography',
                'description' => 'Web typography, font selection, readability, and text styling.',
                'color' => '#F97316',
                'sort_order' => 56,
                'is_active' => true,
            ],
            [
                'name' => 'Animation',
                'slug' => 'animation',
                'description' => 'CSS animations, JavaScript animations, transitions, and motion design.',
                'color' => '#84CC16',
                'sort_order' => 57,
                'is_active' => true,
            ],
            [
                'name' => 'Browser APIs',
                'slug' => 'browser-apis',
                'description' => 'Web APIs, DOM manipulation, Fetch API, Geolocation, and browser capabilities.',
                'color' => '#A855F7',
                'sort_order' => 58,
                'is_active' => true,
            ],
            [
                'name' => 'Web Components',
                'slug' => 'web-components',
                'description' => 'Custom elements, shadow DOM, HTML templates, and component architecture.',
                'color' => '#EC4899',
                'sort_order' => 59,
                'is_active' => true,
            ],
            [
                'name' => 'State Management',
                'slug' => 'state-management',
                'description' => 'Redux, Zustand, MobX, state management patterns, and application state.',
                'color' => '#0EA5E9',
                'sort_order' => 60,
                'is_active' => true,
            ],
            [
                'name' => 'Mobile Reviews',
                'slug' => 'mobile-reviews',
                'description' => 'Smartphone reviews, mobile device comparisons, and phone buying guides.',
                'color' => '#3B82F6',
                'sort_order' => 61,
                'is_active' => true,
            ],
            [
                'name' => 'Laptop Reviews',
                'slug' => 'laptop-reviews',
                'description' => 'Laptop reviews, notebook comparisons, and laptop buying guides.',
                'color' => '#10B981',
                'sort_order' => 62,
                'is_active' => true,
            ],
            [
                'name' => 'Tablet Reviews',
                'slug' => 'tablet-reviews',
                'description' => 'Tablet reviews, iPad alternatives, and tablet buying guides.',
                'color' => '#8B5CF6',
                'sort_order' => 63,
                'is_active' => true,
            ],
            [
                'name' => 'Smartwatch Reviews',
                'slug' => 'smartwatch-reviews',
                'description' => 'Smartwatch reviews, fitness trackers, and wearable device comparisons.',
                'color' => '#EF4444',
                'sort_order' => 64,
                'is_active' => true,
            ],
            [
                'name' => 'Headphones & Audio',
                'slug' => 'headphones-audio',
                'description' => 'Headphone reviews, earbuds, speakers, and audio equipment reviews.',
                'color' => '#F59E0B',
                'sort_order' => 65,
                'is_active' => true,
            ],
            [
                'name' => 'Camera Reviews',
                'slug' => 'camera-reviews',
                'description' => 'Camera reviews, DSLR, mirrorless, action cameras, and photography gear.',
                'color' => '#06B6D4',
                'sort_order' => 66,
                'is_active' => true,
            ],
            [
                'name' => 'Gaming Hardware',
                'slug' => 'gaming-hardware',
                'description' => 'Gaming PC reviews, graphics cards, gaming mice, keyboards, and gaming peripherals.',
                'color' => '#EC4899',
                'sort_order' => 67,
                'is_active' => true,
            ],
            [
                'name' => 'Software Reviews',
                'slug' => 'software-reviews',
                'description' => 'Software application reviews, productivity tools, and software comparisons.',
                'color' => '#6366F1',
                'sort_order' => 68,
                'is_active' => true,
            ],
            [
                'name' => 'App Reviews',
                'slug' => 'app-reviews',
                'description' => 'Mobile app reviews, iOS apps, Android apps, and app recommendations.',
                'color' => '#14B8A6',
                'sort_order' => 69,
                'is_active' => true,
            ],
            [
                'name' => 'Smart Home Devices',
                'slug' => 'smart-home-devices',
                'description' => 'Smart home product reviews, IoT devices, smart speakers, and home automation.',
                'color' => '#F97316',
                'sort_order' => 70,
                'is_active' => true,
            ],
            [
                'name' => 'Monitors & Displays',
                'slug' => 'monitors-displays',
                'description' => 'Monitor reviews, display technology, 4K monitors, and screen comparisons.',
                'color' => '#84CC16',
                'sort_order' => 71,
                'is_active' => true,
            ],
            [
                'name' => 'Storage Devices',
                'slug' => 'storage-devices',
                'description' => 'SSD reviews, hard drives, USB drives, and storage solutions.',
                'color' => '#A855F7',
                'sort_order' => 72,
                'is_active' => true,
            ],
            [
                'name' => 'Networking Equipment',
                'slug' => 'networking-equipment',
                'description' => 'Router reviews, modems, network switches, and networking hardware.',
                'color' => '#EC4899',
                'sort_order' => 73,
                'is_active' => true,
            ],
            [
                'name' => 'Power Banks & Chargers',
                'slug' => 'power-banks-chargers',
                'description' => 'Power bank reviews, wireless chargers, and charging accessories.',
                'color' => '#0EA5E9',
                'sort_order' => 74,
                'is_active' => true,
            ],
            [
                'name' => 'Drones & Robotics',
                'slug' => 'drones-robotics',
                'description' => 'Drone reviews, robotics kits, and autonomous device reviews.',
                'color' => '#22C55E',
                'sort_order' => 75,
                'is_active' => true,
            ],
            [
                'name' => 'VR & AR Devices',
                'slug' => 'vr-ar-devices',
                'description' => 'Virtual reality headsets, AR glasses, and immersive technology reviews.',
                'color' => '#F59E0B',
                'sort_order' => 76,
                'is_active' => true,
            ],
            [
                'name' => 'Printers & Scanners',
                'slug' => 'printers-scanners',
                'description' => 'Printer reviews, scanner reviews, and office equipment.',
                'color' => '#8B5CF6',
                'sort_order' => 77,
                'is_active' => true,
            ],
            [
                'name' => 'Keyboards & Mice',
                'slug' => 'keyboards-mice',
                'description' => 'Mechanical keyboards, gaming mice, and input device reviews.',
                'color' => '#06B6D4',
                'sort_order' => 78,
                'is_active' => true,
            ],
            [
                'name' => 'Webcams & Streaming',
                'slug' => 'webcams-streaming',
                'description' => 'Webcam reviews, streaming equipment, and content creation gear.',
                'color' => '#EF4444',
                'sort_order' => 79,
                'is_active' => true,
            ],
            [
                'name' => 'Projectors',
                'slug' => 'projectors',
                'description' => 'Projector reviews, home theater projectors, and portable projectors.',
                'color' => '#10B981',
                'sort_order' => 80,
                'is_active' => true,
            ],
            [
                'name' => 'Security Cameras',
                'slug' => 'security-cameras',
                'description' => 'Security camera reviews, home security systems, and surveillance equipment.',
                'color' => '#3B82F6',
                'sort_order' => 81,
                'is_active' => true,
            ],
            [
                'name' => 'E-readers',
                'slug' => 'e-readers',
                'description' => 'E-reader reviews, Kindle alternatives, and digital reading devices.',
                'color' => '#6366F1',
                'sort_order' => 82,
                'is_active' => true,
            ],
            [
                'name' => 'Fitness Tech',
                'slug' => 'fitness-tech',
                'description' => 'Fitness tracker reviews, smart scales, and health monitoring devices.',
                'color' => '#14B8A6',
                'sort_order' => 83,
                'is_active' => true,
            ],
            [
                'name' => 'Car Tech',
                'slug' => 'car-tech',
                'description' => 'Car technology reviews, dash cams, GPS devices, and automotive tech.',
                'color' => '#F97316',
                'sort_order' => 84,
                'is_active' => true,
            ],
            [
                'name' => 'Accessories',
                'slug' => 'accessories',
                'description' => 'Tech accessories, cases, cables, adapters, and gadget accessories.',
                'color' => '#84CC16',
                'sort_order' => 85,
                'is_active' => true,
            ],
            [
                'name' => 'Budget Tech',
                'slug' => 'budget-tech',
                'description' => 'Budget-friendly tech reviews, affordable gadgets, and value-for-money products.',
                'color' => '#A855F7',
                'sort_order' => 86,
                'is_active' => true,
            ],
            [
                'name' => 'Premium Tech',
                'slug' => 'premium-tech',
                'description' => 'High-end technology reviews, luxury gadgets, and premium product reviews.',
                'color' => '#EC4899',
                'sort_order' => 87,
                'is_active' => true,
            ],
            [
                'name' => 'Product Comparisons',
                'slug' => 'product-comparisons',
                'description' => 'Side-by-side product comparisons, buying guides, and product showdowns.',
                'color' => '#0EA5E9',
                'sort_order' => 88,
                'is_active' => true,
            ],
        ];

        foreach ($categories as $categoryData) {
            Category::firstOrCreate(
                ['slug' => $categoryData['slug']],
                $categoryData
            );
        }

        $this->command->info('✅ Categories seeded successfully!');
    }
}

